# Copyright 2026 SARC Suite Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Milestone E, Step 2 (`prereg/v6.1-authoritybench-amendment.md`, tag
`prereg-p5-v6.1`): writes each of the three registered domains'
`candidate-context.yaml`, `loss-model.yaml`, `reachability.yaml`,
`baseline-manual-policy.yaml`, and `expected-certificates.yaml` under
`authority_bench_domains/<domain>/`. A PACKAGING of what `domain.py`/
`domain_v4.py`/`domain_datacomms.py` already declare in Python (v2's and
v4's own modules are read, not modified -- "science of committed
versions stays frozen") -- for v2/v4, `expected-certificates.yaml`
restates their own ALREADY-COMMITTED, already machine-checked core/
reduct results (`out/checkers/reduct_check.json`,
`out/checkers/ch_b1_check.json`); for the new domain, it restates this
milestone's own `out/checkers/ch_datacomms_check.json`, generated by
`checkers/ch_datacomms_check.py` before this script runs.

Milestone E, Step 4 addendum: `_candidate_context_datacomms` gained an
`observation_cost` field per property, reading `domain_datacomms.py`'s
new `PROPERTY_OBSERVATION_COSTS_DATACOMMS`. The prereg's own "Contract
cost" metric section already promised "REAL declared per-property costs
for the new data-and-communications domain... registered in candidate-
context.yaml, Step 2" -- that promise went unfulfilled when this file
was first written (no cost data existed anywhere yet); completed here,
at Step 4, before the harness that consumes it needed it, rather than
left as a silent gap between the registered text and what Step 2 in
fact shipped. v2's and v4's own candidate-context builders are
unchanged -- no per-property cost data is retroactively invented for
domains whose own preregistrations never declared any (prereg's own
text), so they keep no `observation_cost` field and the harness applies
the uniform floor to them, exactly as `benchmarks.py`'s
`_real_domain_costs` already does elsewhere in this project."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict

import yaml

OUTPUT_ROOT = Path("authority_bench_domains")


def _yaml_safe(value: Any) -> Any:
    """v1/v2's `consumed_grant_ids` is a frozenset-valued candidate
    property (`participation._serialize`'s own long-standing reason for
    existing, `authority_bench.py`'s own identical fix for JSON) --
    converted to a sorted list here too, recursively, only at the YAML
    boundary."""
    if isinstance(value, frozenset):
        return sorted(_yaml_safe(v) for v in value)
    if isinstance(value, (list, tuple)):
        return [_yaml_safe(v) for v in value]
    if isinstance(value, dict):
        return {k: _yaml_safe(v) for k, v in value.items()}
    return value


def _write_yaml(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(_yaml_safe(data), sort_keys=False, default_flow_style=False))


def _candidate_context_v2() -> Dict[str, Any]:
    from domain import CANDIDATE_PROPERTIES_V2, load_pair_test_grid, property_domains_v2

    domains = property_domains_v2(load_pair_test_grid())
    return {"domain": "procurement-v2", "candidate_properties": [{"name": p, "domain": domains[p]} for p in CANDIDATE_PROPERTIES_V2]}


def _candidate_context_v4() -> Dict[str, Any]:
    from domain_v4 import CANDIDATE_PROPERTIES_V4, PROPERTY_DOMAINS_V4

    return {"domain": "software-and-cloud-v4", "candidate_properties": [{"name": p, "domain": PROPERTY_DOMAINS_V4[p]} for p in CANDIDATE_PROPERTIES_V4]}


def _candidate_context_datacomms() -> Dict[str, Any]:
    from domain_datacomms import CANDIDATE_PROPERTIES_DATACOMMS, PROPERTY_DOMAINS_DATACOMMS, PROPERTY_OBSERVATION_COSTS_DATACOMMS

    return {
        "domain": "data-and-communications",
        "candidate_properties": [
            {"name": p, "domain": PROPERTY_DOMAINS_DATACOMMS[p], "observation_cost": PROPERTY_OBSERVATION_COSTS_DATACOMMS[p]}
            for p in CANDIDATE_PROPERTIES_DATACOMMS
        ],
    }


LOSS_MODEL_V2 = {
    "domain": "procurement-v2",
    "losses": [
        {"name": "order_value_beyond_entitlement", "citation": "prereg/loss-model.yaml (v1, carried into v2)"},
        {"name": "procurement_outside_temporal_window", "citation": "prereg/loss-model.yaml (v1, carried into v2)"},
        {"name": "resource_class_not_entitled", "citation": "prereg/loss-model.yaml (v1, carried into v2)"},
        {"name": "replayed_consumed_grant", "citation": "prereg/loss-model.yaml (v1, carried into v2)"},
        {"name": "spend_against_depleted_delegated_budget", "citation": "prereg/loss-model.yaml (v1, carried into v2)"},
        {"name": "action_on_frozen_control_state", "citation": "prereg/loss-model.yaml (v1, carried into v2)"},
    ],
}

LOSS_MODEL_V4 = {
    "domain": "software-and-cloud-v4",
    "losses": [
        {"name": "unauthorised_mutation", "citation": "rbac-sandhu-1996"},
        {"name": "production_deployment_without_approval", "citation": "nist-sp-800-53-cm3"},
        {"name": "secret_exposure", "citation": "cwe-798"},
        {"name": "cross_tenant_action", "citation": "csa-ccm-tenant-isolation"},
        {"name": "privilege_escalation", "citation": "mitre-attack-ta0004-privilege-escalation"},
        {"name": "destructive_action_without_recovery_path", "citation": "mitre-attack-t1485-data-destruction"},
    ],
}

LOSS_MODEL_DATACOMMS = {
    "domain": "data-and-communications",
    "losses": [
        {"name": "unlawful_processing", "citation": "gdpr-2016-679 (Art. 6)"},
        {"name": "special_category_without_basis", "citation": "gdpr-2016-679 (Art. 9)"},
        {"name": "unsafeguarded_transfer", "citation": "gdpr-2016-679 (Art. 44)"},
        {"name": "retention_violation", "citation": "gdpr-2016-679 (Art. 5(1)(e))"},
        {"name": "unconfidential_channel", "citation": "eprivacy-directive-2002-58 (Art. 5)"},
        {"name": "unfulfilled_erasure", "citation": "gdpr-2016-679 (Art. 17)"},
    ],
}

REACHABILITY_V2 = {
    "domain": "procurement-v2",
    "rules": [
        {
            "name": "min_order_quantity_cross_field_filter",
            "description": "prereg/v2-reachability-redesign.md's own declared rank-0 filter: order_value >= min_order_quantity.",
        }
    ],
}

REACHABILITY_V4 = {
    "domain": "software-and-cloud-v4",
    "rules": [
        {"name": "production_branch_implies_production_environment", "description": "prereg/v4-realistic-domain.md's first reachability rule."},
        {"name": "contractor_readonly_tenant_scope", "description": "prereg/v4-realistic-domain.md's second reachability rule (delegated_role implies resource_owner scope, narrowed to role-contractor-readonly)."},
    ],
}

REACHABILITY_DATACOMMS = {
    "domain": "data-and-communications",
    "rules": [
        {
            "name": "internal_only_stays_in_eea",
            "description": "recipient_type == internal_only implies destination_region == eea (prereg/v6.1-authoritybench-amendment.md).",
        }
    ],
}

BASELINE_MANUAL_POLICY_V2 = {
    "domain": "procurement-v2",
    "policy_name": "manual-least-privilege",
    "attributes": ["actor_role", "order_value", "resource_class", "budget_remaining"],
    "rationale": (
        "hand-authored by a security-conscious reviewer without formal derivation: the 'obviously relevant' "
        "business-risk properties. Registered as plausibly missing grant_id/consumed_grant_ids (replay-prevention "
        "machinery, not obvious without deliberate replay-threat modelling), day/frozen (temporal/freeze-state "
        "conditions), and min_order_quantity."
    ),
}

BASELINE_MANUAL_POLICY_V4 = {
    "domain": "software-and-cloud-v4",
    "policy_name": "manual-least-privilege",
    "attributes": ["delegated_role", "operation", "approval_token", "environment"],
    "rationale": (
        "a conventional RBAC-plus-change-control set. Registered as plausibly missing resource_owner (cross-tenant "
        "isolation, easy to overlook without deliberate multi-tenant threat modelling -- CH-B1's own counterexample "
        "pair already turns on exactly this kind of gap), repository, and data_classification."
    ),
}

BASELINE_MANUAL_POLICY_DATACOMMS = {
    "domain": "data-and-communications",
    "policy_name": "manual-least-privilege",
    "attributes": ["data_category", "legal_basis", "destination_region", "channel_encryption"],
    "rationale": (
        "the 'obviously GDPR-flavoured' properties. Registered as plausibly missing retention_status and "
        "erasure_request_state (ongoing-obligation controls, easy to treat as a process concern rather than a "
        "gating one)."
    ),
}


def _expected_certificates_v2() -> Dict[str, Any]:
    reduct_check = json.loads(Path("out/checkers/reduct_check.json").read_text())
    return {
        "domain": "procurement-v2",
        "source": "out/checkers/reduct_check.json (CH-A8/CH-A10, already committed, already machine-checked)",
        "core_attributes": reduct_check["core_attributes"],
        "core_is_unique_reduct": reduct_check["core_is_unique_reduct"],
        "minimum_reducts": reduct_check["minimum_reducts"],
        "minimum_reduct_cardinality": reduct_check["minimum_reduct_cardinality"],
    }


def _expected_certificates_v4() -> Dict[str, Any]:
    ch_b1 = json.loads(Path("out/checkers/ch_b1_check.json").read_text())
    return {
        "domain": "software-and-cloud-v4",
        "source": "out/checkers/ch_b1_check.json (CH-B1, already committed, already machine-checked)",
        "core_attributes": ch_b1["core_attributes"],
        "is_core_sufficient": ch_b1["is_core_sufficient"],
        "minimum_reducts": ch_b1["minimum_reducts"],
        "minimum_reduct_cardinality": ch_b1["minimum_reduct_cardinality"],
    }


def _expected_certificates_datacomms() -> Dict[str, Any]:
    """Per the registration's own discipline: only the structural facts
    defended in advance (not a pre-computed core/reduct) -- the
    STRUCTURAL claims (the reachability rule's effect;
    actor_role/recipient_type's non-participation) are what was
    registered; the actual measured outcome (checkers/ch_datacomms_
    check.py) is included too, generated by this milestone's own
    implementation, not asserted at registration time."""
    ch_dc1 = json.loads(Path("out/checkers/ch_datacomms_check.json").read_text())
    return {
        "domain": "data-and-communications",
        "registered_structural_claims": [
            "the internal_only_stays_in_eea reachability rule narrows the reachable set below the full 11,520-tuple product to 8,640",
            "actor_role is read by no loss predicate, hence structurally forced non-participating",
        ],
        "measured_outcome_source": "out/checkers/ch_datacomms_check.json (CH-DC1, generated by this milestone's own implementation, not asserted at registration time)",
        "core_attributes": ch_dc1["core_attributes"],
        "core_is_sufficient": ch_dc1["core_is_sufficient"],
        "minimum_reducts": ch_dc1["minimum_reducts"],
        "minimum_reduct_cardinality": ch_dc1["minimum_reduct_cardinality"],
        "redundant_attributes": ch_dc1["redundant_attributes"],
    }


def build() -> None:
    domains = [
        ("v2", _candidate_context_v2, LOSS_MODEL_V2, REACHABILITY_V2, BASELINE_MANUAL_POLICY_V2, _expected_certificates_v2),
        ("v4", _candidate_context_v4, LOSS_MODEL_V4, REACHABILITY_V4, BASELINE_MANUAL_POLICY_V4, _expected_certificates_v4),
        ("data-and-communications", _candidate_context_datacomms, LOSS_MODEL_DATACOMMS, REACHABILITY_DATACOMMS, BASELINE_MANUAL_POLICY_DATACOMMS, _expected_certificates_datacomms),
    ]
    for name, candidate_context_fn, loss_model, reachability, manual_policy, expected_certificates_fn in domains:
        domain_dir = OUTPUT_ROOT / name
        _write_yaml(domain_dir / "candidate-context.yaml", candidate_context_fn())
        _write_yaml(domain_dir / "loss-model.yaml", loss_model)
        _write_yaml(domain_dir / "reachability.yaml", reachability)
        _write_yaml(domain_dir / "baseline-manual-policy.yaml", manual_policy)
        _write_yaml(domain_dir / "expected-certificates.yaml", expected_certificates_fn())
        print(f"wrote {domain_dir}/{{candidate-context,loss-model,reachability,baseline-manual-policy,expected-certificates}}.yaml")


if __name__ == "__main__":
    build()
